odiseo_pickmystuff_backend_address_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: odiseo_pickmystuff.controller.address:indexAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/Address:index.html.twig
            paginate: 100
            sortable: true
            sorting: { id: desc }

odiseo_pickmystuff_backend_address_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: odiseo_pickmystuff.controller.address:createAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/Address:create.html.twig
            redirect: odiseo_pickmystuff_backend_address_update

odiseo_pickmystuff_backend_address_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: odiseo_pickmystuff.controller.address:updateAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/Address:update.html.twig
            redirect: odiseo_pickmystuff_backend_order_index

odiseo_pickmystuff_backend_address_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: odiseo_pickmystuff.controller.address:deleteAction
        _sylius:
            redirect: odiseo_pickmystuff_backend_address_index