odiseo_pickmystuff_backend_carrier_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: odiseo_pickmystuff.controller.carrier:indexAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/carrier:index.html.twig
            paginate: 100

odiseo_pickmystuff_backend_carrier_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: odiseo_pickmystuff.controller.carrier:createAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/carrier:create.html.twig
            redirect: odiseo_pickmystuff_backend_carrier_update

odiseo_pickmystuff_backend_carrier_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: odiseo_pickmystuff.controller.carrier:updateAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/carrier:update.html.twig
            redirect: odiseo_pickmystuff_backend_carrier_update

odiseo_pickmystuff_backend_carrier_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: odiseo_pickmystuff.controller.carrier:deleteAction
        _sylius:
            redirect: odiseo_pickmystuff_backend_carrier_index