odiseo_pickmystuff_backend_mercancy_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: odiseo_pickmystuff.controller.mercancy:indexAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/Mercancy:index.html.twig
            paginate: 100

odiseo_pickmystuff_backend_mercancy_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: odiseo_pickmystuff.controller.mercancy:createAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/Mercancy:create.html.twig
            redirect: odiseo_pickmystuff_backend_mercancy_update

odiseo_pickmystuff_backend_mercancy_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: odiseo_pickmystuff.controller.mercancy:updateAction
        _sylius:
            template: OdiseoPickMyStuffBundle:Backend/Mercancy:update.html.twig
            redirect: odiseo_pickmystuff_backend_mercancy_update

odiseo_pickmystuff_backend_mercancy_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: odiseo_pickmystuff.controller.mercancy:deleteAction
        _sylius:
            redirect: odiseo_pickmystuff_backend_mercancy_index