odiseo_pickmystuff_backend_security_login:
    pattern: /login
    methods: [GET]
    defaults:
        _controller: OdiseoPickMyStuffBundle:Backend/Security:login

odiseo_pickmystuff_backend_security_login_check:
    pattern: /login-check
    methods: [POST]
    defaults:
        _controller: OdiseoPickMyStuffBundle:Backend/Security:check

odiseo_pickmystuff_backend_security_logout:
    pattern: /logout
    methods: [GET]
    defaults:
        _controller: OdiseoPickMyStuffBundle:Backend/Security:logout