odiseo_pick_my_stuff_frontend:
    resource: "@OdiseoPickMyStuffBundle/Resources/config/routing/frontend/main.yml"
    prefix:   /

odiseo_pick_my_stuff_backend:
    resource: "@OdiseoPickMyStuffBundle/Resources/config/routing/backend/main.yml"
    prefix:   /admin

_imagine:
    resource: .
    type:     imagine
