odiseo_pick_my_stuff_frontend_home:
    path:     /
    defaults: { _controller: "OdiseoPickMyStuffBundle:Frontend/Home:index" }

odiseo_pick_my_stuff_frontend_order:
    path:     /order
    defaults: { _controller: "OdiseoPickMyStuffBundle:Frontend/Home:order" }

odiseo_pick_my_stuff_frontend_home_submit:
    path:     /submit
    defaults: { _controller: "OdiseoPickMyStuffBundle:Frontend/Home:submit" }
    
odiseo_pick_my_stuff_frontend_home_add:
    path:     /add/{id}
    defaults: { _controller: "OdiseoPickMyStuffBundle:Frontend/Home:submitAdd" }

odiseo_pick_my_stuff_frontend_aboutus:
    path:     /aboutus
    defaults: { _controller: "OdiseoPickMyStuffBundle:Frontend/Home:aboutUs" }

odiseo_pick_my_stuff_frontend_contact:
    path:     /contact
    defaults: { _controller: "OdiseoPickMyStuffBundle:Frontend/Home:contact" }

odiseo_pick_my_stuff_frontend_questions:
    path:     /services
    defaults: { _controller: "OdiseoPickMyStuffBundle:Frontend/Home:services" }

odiseo_pickmystuff_costumerform:
    pattern: /contact_form
    methods: [POST]
    defaults:
        _controller: OdiseoPickMyStuffBundle:Frontend/Costumer:index

#FosUserBundle Routes
#fos_user_security_frontend:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#    prefix: /

#fos_user_register_frontend:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#	    prefix: /register