Odiseo\Bundle\PickMyStuffBundle\Entity\Carrier:
    type: entity
    table: carrier
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        vehicleType:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToMany:
        orders:
            targetEntity: Order
            mappedBy: carrier
    lifecycleCallbacks: {  }
