Odiseo\Bundle\PickMyStuffBundle\Entity\Carrier:
    type: entity
    table: carrier
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        vehicleType:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        isPaid:
            type: boolean
            nullable: true
        photoTruck:
            type: boolean
            nullable: true
        commissionPermits:
            type: boolean
            nullable: true
        portsPermits:
            type: boolean
            nullable: true
        carPolicy:
            type: boolean
            nullable: true
        mercancyPolicy:
            type: boolean
            nullable: true
        responsabilityPolicy:
            type: boolean
            nullable: true
        contractPickmystuff:
            type: boolean
            nullable: true
        originTown:
            type: string
            length: 255
            nullable: true
        destinationTown:
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToMany:
        orders:
            targetEntity: Order
            mappedBy: carrier
    lifecycleCallbacks: {  }
