Odiseo\Bundle\PickMyStuffBundle\Entity\Order:
    type: entity
    table: order_client
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: string
            length: 255
            nullable: true
        collectedTime:
            type: string
            length: 255
            nullable: true
        deliveryTime:
            type: string
            length: 255
            nullable: true
        comments:
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update
    oneToOne:
        mercancy:
            targetEntity: Mercancy
            mappedBy: order
            cascade: ["persist", "merge"]
    manyToOne:
        client:
            targetEntity: Client
            inversedBy: orders
            cascade: ["persist", "merge"]
            joinColumn:
                name: client_id
                referencedColumnName: id
                onDelete: SET NULL
        carrier:
            targetEntity: Carrier
            inversedBy: orders
            cascade: ["persist", "merge"]
            joinColumn:
                name: carrier_id
                referencedColumnName: id
                onDelete: SET NULL
        sourceAddress:
            targetEntity: Address
            inversedBy: orders
            cascade: ["persist", "merge"]
            joinColumn:
              name: sourceAddress_id
              referencedColumnName: id
              onDelete: SET NULL
        destinationAddress:
            targetEntity: Address
            inversedBy: orders
            cascade: ["persist", "merge"]
            joinColumn:
              name: destinationAddress_id
              referencedColumnName: id
              onDelete: SET NULL
    lifecycleCallbacks: {  }
